-------------------------------------
-- Create Database ------------------
-------------------------------------

USE master;
GO

CREATE DATABASE bobshirt;
GO

USE bobshirt;
GO

-------------------------------------
-- Normal Tables --------------------
-------------------------------------

CREATE TABLE CUSTOMER (
    CUSTOMERID INTEGER NOT NULL,
    ADDRESSID INTEGER NOT NULL,
    [NAME] VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONENR VARCHAR(20),
    SIGNUPDATE DATE,
    PASSWORDHASH VARCHAR(256),
    ISADMIN BIT DEFAULT 0
);
CREATE TABLE ADDRESS (
    ADDRESSID INTEGER NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    HOUSENUMBER VARCHAR(50) NOT NULL,
    POSTALCODE VARCHAR(10) NOT NULL,
    CITY VARCHAR(50) NOT NULL
);
CREATE TABLE [ORDER] (
    ORDERID INTEGER NOT NULL,
    CUSTOMERID INTEGER NOT NULL,
    ORDERDATE DATE NOT NULL,
    TOTALAMOUNT DECIMAL(10,2) NOT NULL
);
CREATE TABLE PRODUCT (
    PRODUCTID INTEGER NOT NULL,
    PRODUCTNAME VARCHAR(100),
    PRICE DECIMAL(5,2),
    TYPEID INTEGER NOT NULL
);
CREATE TABLE PAYMENT (
    PAYMENTID INTEGER NOT NULL,
    ORDERID INTEGER NOT NULL,
    PAYMENTDATE DATE NOT NULL,
    PROCESSORID INTEGER NOT NULL
);
CREATE TABLE PAYMENTPROCESSOR (
    PROCESSORID INTEGER NOT NULL,
    METHOD VARCHAR(50) NOT NULL
);
CREATE TABLE PRODUCT_TYPE (
    TYPEID INTEGER NOT NULL,
    TYPENAME VARCHAR(100) NOT NULL
);
CREATE TABLE COLOR (
    COLORID INTEGER NOT NULL,
    COLORNAME VARCHAR(20) NOT NULL
);
CREATE TABLE [SIZE] (
    SIZEID INTEGER NOT NULL,
    SIZENAME VARCHAR(50) NOT NULL,
    PRICEMULTIPLIER DECIMAL(10,2) NOT NULL
);
CREATE TABLE SHIPMENT (
    SHIPMENTID INTEGER NOT NULL,
    ORDERID INTEGER NOT NULL,
    ESTIMATEDDELIVERYDATE DATE,
    SHIPMENTSTATUS VARCHAR(50),
    SHIPPINGCOST DECIMAL(10,2) NOT NULL
);
-------------------------------------
-- Junction Tables ------------------
-------------------------------------

CREATE TABLE PRODUCT_VARIANT  (
    VARIANTID INTEGER NOT NULL,
    PRODUCTID INTEGER NOT NULL,
    COLORID INTEGER NOT NULL,
    SIZEID INTEGER NOT NULL,
    STOCK INTEGER
);

CREATE TABLE ORDER_ITEM (
    ORDERID INTEGER NOT NULL,
    VARIANTID INTEGER NOT NULL,
    AMOUNT INTEGER NOT NULL
);