USE master;
GO

CREATE DATABASE bobshirt;
GO

USE bobshirt;
GO

CREATE TABLE CUSTOMER (
    CUSTOMERID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ADDRESSID INTEGER NOT NULL,
    PHONENR VARCHAR(20),
    SIGNUPDATE DATE
);
CREATE TABLE ADDRESS (
    ADDRESSID INTEGER NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    HOUSENUMBER VARCHAR(50) NOT NULL,
    POSTALCODE INTEGER NOT NULL,
    CITY VARCHAR(50) NOT NULL
);
CREATE TABLE [ORDER] (
    ORDERID INTEGER NOT NULL,
    CUSTOMERID INTEGER NOT NULL,
    CARTID INTEGER NOT NULL,
    ORDERDATE DATE NOT NULL,
    TOTALAMOUNT DECIMAL(10,2) NOT NULL
);
CREATE TABLE PAYMENT (
    PAYMENTID INTEGER NOT NULL,
    ORDERID INTEGER NOT NULL,
    PAYMENTDATE DATE NOT NULL,
    PROCESSORID INTEGER NOT NULL
);
CREATE TABLE PAYMENTPROCESSOR (
    PROCESSORID INTEGER NOT NULL,
    METHOD VARCHAR(50) NOT NULL
);
CREATE TABLE ITEM (
    ITEMID INTEGER NOT NULL,
    ITEMNAME VARCHAR(100),
    SIZE VARCHAR(10),
    COLOR VARCHAR(30),
    PRIZE DECIMAL(5,2)
);
CREATE TABLE CART (
    CARTID INTEGER NOT NULL,
    ITEMID INTEGER NOT NULL,
);
