USE bobshirt;

-------------------------------------
-- Foreign Keys ---------------------
-------------------------------------

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (ADDRESSID)
    REFERENCES ADDRESS(ADDRESSID)

ALTER TABLE [ORDER]
ADD CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMER(CUSTOMERID)

ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_PRODUCTTYPE FOREIGN KEY(TYPEID)
    REFERENCES PRODUCT_TYPE(TYPEID)
    ON DELETE CASCADE

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (ORDERID)
    REFERENCES [ORDER](ORDERID)
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_PROCESSOR FOREIGN KEY (PROCESSORID)
    REFERENCES PAYMENTPROCESSOR(PROCESSORID)

ALTER TABLE PRODUCT_VARIANT
ADD CONSTRAINT FK_PRODUCTVARIANT_PRODUCT FOREIGN KEY (PRODUCTID) 
    REFERENCES PRODUCT(PRODUCTID)
    ON DELETE CASCADE
ALTER TABLE PRODUCT_VARIANT
ADD CONSTRAINT FK_PRODUCTVARIANT_SIZE FOREIGN KEY (SIZEID)
    REFERENCES [SIZE](SIZEID)
    ON DELETE CASCADE
ALTER TABLE PRODUCT_VARIANT
ADD CONSTRAINT FK_PRODUCTVARIANT_COLOR FOREIGN KEY (COLORID)
    REFERENCES COLOR(COLORID)
    ON DELETE CASCADE
ALTER TABLE PRODUCT_VARIANT
ADD CONSTRAINT UNIQUE_VARIANT UNIQUE (PRODUCTID, COLORID, SIZEID)
