USE bobshirt;

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (ADDRESSID)
    REFERENCES ADDRESS(ADDRESSID)

ALTER TABLE [ORDER]
ADD CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMER(CUSTOMERID)
ALTER TABLE [ORDER]
ADD CONSTRAINT FK_ORDER_CART FOREIGN KEY (CARTID)
    REFERENCES CART(CARTID)

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (ORDERID)
    REFERENCES [ORDER](ORDERID)
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_PROCESSOR FOREIGN KEY (PROCESSORID)
    REFERENCES PAYMENTPROCESSOR(PROCESSORID)

ALTER TABLE CART
ADD CONSTRAINT FK_CART_ITEM FOREIGN KEY (ITEMID)
    REFERENCES ITEM(ITEMID)