USE bobshirt;

-------------------------------------
-- Foreign Keys ---------------------
-------------------------------------

ALTER TABLE CUSTOMER
ADD CONSTRAINT FK_CUSTOMER_ADDRESS FOREIGN KEY (ADDRESSID)
    REFERENCES ADDRESS(ADDRESSID)

ALTER TABLE [ORDER]
ADD CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMERID)
    REFERENCES CUSTOMER(CUSTOMERID)

ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_ORDER FOREIGN KEY (ORDERID)
    REFERENCES [ORDER](ORDERID)
ALTER TABLE PAYMENT
ADD CONSTRAINT FK_PAYMENT_PROCESSOR FOREIGN KEY (PROCESSORID)
    REFERENCES PAYMENTPROCESSOR(PROCESSORID)