USE bobshirt;

-------------------------------------
-- Primary Keys ---------------------
-------------------------------------

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMERID PRIMARY KEY(CUSTOMERID)

ALTER TABLE [ORDER]
ADD CONSTRAINT PK_ORDERID PRIMARY KEY(ORDERID)

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY(PRODUCTID)

ALTER TABLE ADDRESS
ADD CONSTRAINT PK_ADDRESSID PRIMARY KEY(ADDRESSID)

ALTER TABLE PAYMENT
ADD CONSTRAINT PK_PAYMENTID PRIMARY KEY(PAYMENTID)

ALTER TABLE PAYMENTPROCESSOR
ADD CONSTRAINT PK_PROCESSORID PRIMARY KEY(PROCESSORID)

ALTER TABLE COLOR
ADD CONSTRAINT PK_COLOR PRIMARY KEY(COLORID)

ALTER TABLE PRODUCT_TYPE
ADD CONSTRAINT PK_PRODUCTTYPE PRIMARY KEY(TYPEID)

ALTER TABLE [SIZE]
ADD CONSTRAINT PK_SIZE PRIMARY KEY(SIZEID)

ALTER TABLE SHIPMENT
ADD CONSTRAINT PK_SHIPMENT PRIMARY KEY(SHIPMENTID)
-------------------------------------
-- Primary Keys for Junction Tables
-------------------------------------

ALTER TABLE PRODUCT_VARIANT
ADD CONSTRAINT PK_PRODUCTVARIANT PRIMARY KEY(VARIANTID)

ALTER TABLE ORDER_ITEM
ADD CONSTRAINT PK_ORDER_ITEM PRIMARY KEY(PRODUCTID, ORDERID)
