USE bobshirt;

-------------------------------------
-- Primary Keys ---------------------
-------------------------------------

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMERID PRIMARY KEY(CUSTOMERID)

ALTER TABLE [ORDER]
ADD CONSTRAINT PK_ORDERID PRIMARY KEY(ORDERID)

ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY(PRODUCTID)

ALTER TABLE ADDRESS
ADD CONSTRAINT PK_ADDRESSID PRIMARY KEY(ADDRESSID)

ALTER TABLE PAYMENT
ADD CONSTRAINT PK_PAYMENTID PRIMARY KEY(PAYMENTID)

ALTER TABLE PAYMENTPROCESSOR
ADD CONSTRAINT PK_PROCESSORID PRIMARY KEY(PROCESSORID)

-------------------------------------
-- Primary Keys for Junction Tables
-------------------------------------

ALTER TABLE ORDER_ITEM
ADD CONSTRAINT PK_ORDER_ITEM PRIMARY KEY(PRODUCTID,ORDERID)
