USE bobshirt;

ALTER TABLE CUSTOMER
ADD CONSTRAINT PK_CUSTOMERID PRIMARY KEY(CUSTOMERID)

ALTER TABLE [ORDER]
ADD CONSTRAINT PK_ORDERID PRIMARY KEY(ORDERID)

ALTER TABLE ADDRESS
ADD CONSTRAINT PK_ADDRESSID PRIMARY KEY(ADDRESSID)

ALTER TABLE PAYMENT
ADD CONSTRAINT PK_PAYMENTID PRIMARY KEY(PAYMENTID)

ALTER TABLE PAYMENTPROCESSOR
ADD CONSTRAINT PK_PROCESSORID PRIMARY KEY(PROCESSORID)

ALTER TABLE ITEM
ADD CONSTRAINT PK_ITEMID PRIMARY KEY(ITEMID)

ALTER TABLE CART
ADD CONSTRAINT PK_CARTID PRIMARY KEY(CARTID)
